const routes = {
    AUTH: {
      SIGN_IN: "/auth/sign-in",
      SIGN_UP: "/auth/sign-up",
      FORGOT_PASSWORD: "/auth/forgot-password",
      RESET_PASSWORD: "/reset-password",
      VERIFICATION: "/verification",
      VERIFICATION_SUCCESS: "/verification/success",
      VERIFICATION_FAILED: "/verification/failed",
      SIGN_IN_SUCCESS: "/auth/success",
    },
    CUSTOMER: {
      HOME: "/",
      PRODUCT_DETAIL: "/product/:productId",
      CART: "/checkout/cart",
      CHECKOUT: "/checkout/payment",
      PURCHASE: "/customer/purchase",
      ORDER_DETAIL: "/customer/purchase/:orderId",
      ACCOUNT_PROFILE: "/customer/account/profile",
      ACCOUNT_ADDRESS: "/customer/account/address",
      CHANGE_PASSWORD: "/customer/account/password",
    },
    ADMIN: {
      DASHBOAD: "/dashboad",
      ORDER: "/portal/order",
      ORDER_DETAIL: "/portal/order/:orderId",
      PRODUCT: "/portal/product",
      ADD_PRODUCT: "/portal/product/new",
      PRODUCT_DETAIL: "/portal/product/:productId",
      CATEGORY: "/portal/category",
      REVIEW: "/portal/rating",
      PRODUCT_REPORT: "/datacenter/product/overview",
      INCOME_REPORT: "/datacenter/income/overview",
      ACCOUNT_PROFILE: "/admin/account/profile",
      CHANGE_PASSWORD: "/admin/account/password",
      CUSTOMER: "/admin/customer",
      EMPLOYEE: "/admin/employee",
      ADD_EMPLOYEE: "/portal/employee/new",
    },
  };
  export default routes;
  